services:
  - type: web
    name: automated-research-duplication-detector
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: PORT
        value: 7860
